# Generated by Django 4.2.6 on 2023-11-28 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='timestamp',
            new_name='date_published',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
    ]
